# Services deployed on Raspberry Pi

services:
  kronoterm2mqtt:
    container_name: kronoterm2mqtt
    command: /kronoterm2mqtt/cli.py publish-loop
    build:
      context: deployment/kronoterm2mqtt
      dockerfile: Dockerfile
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  mosquitto:
    image: eclipse-mosquitto:2.0.21
    volumes:
      - ./deployment/mosquitto/:/mosquitto/config/
    ports:
      - "1883:1883"
