services:
  hass:
    container_name: hass
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    ports:
      - "8123:8123"

  mosquitto:
    image: eclipse-mosquitto:2.0.21
    volumes:
      - ../src/deployment/mosquitto/:/mosquitto/config/
    ports:
      - "1883:1883"
