# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.kronoterm_integration: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.26.0.0/16

automation: !include automations.yaml